export const subjectsData = [
  { subject: "Computer Fundamentals and Applications", year: 1, semester: 1 },
  { subject: "Society and Technology", year: 1, semester: 1 },
  { subject: "English I", year: 1, semester: 1 },
  { subject: "Mathematics I", year: 1, semester: 1 },
  { subject: "Digital Logic", year: 1, semester: 1 },
  { subject: "C Programming", year: 1, semester: 2 },
  { subject: "Financial Accounting", year: 1, semester: 2 },
  { subject: "English II", year: 1, semester: 2 },
  { subject: "Mathematics II", year: 1, semester: 2 },
  { subject: "Microprocessor and Computer Architecture", year: 1, semester: 2 },
  { subject: "Data Structures and Algorithms", year: 2, semester: 3 },
  { subject: "Probability and Statistics", year: 2, semester: 3 },
  { subject: "System Analysis and Design", year: 2, semester: 3 },
  { subject: "OOP in Java", year: 2, semester: 3 },
  { subject: "Web Technology", year: 2, semester: 3 },
  { subject: "Operating System", year: 2, semester: 4 },
  { subject: "Numerical Methods", year: 2, semester: 4 },
  { subject: "Software Engineering", year: 2, semester: 4 },
  { subject: "Scripting Language", year: 2, semester: 4 },
  { subject: "Database Management System", year: 2, semester: 4 },
  { subject: "MIS and E-Business", year: 3, semester: 5 },
  { subject: "DotNet Technology", year: 3, semester: 5 },
  { subject: "Computer Networking", year: 3, semester: 5 },
  { subject: "Introduction to Management", year: 3, semester: 5 },
  { subject: "Computer Graphics and Animation", year: 3, semester: 5 },
  { subject: "Mobile Programming", year: 3, semester: 6 },
  { subject: "Distributed System", year: 3, semester: 6 },
  { subject: "Applied Economics", year: 3, semester: 6 },
  { subject: "Advanced Java Programming", year: 3, semester: 6 },
  { subject: "Network Programming", year: 3, semester: 6 },
  { subject: "Cyber Law and Professional Ethics", year: 4, semester: 7 },
  { subject: "Cloud Computing", year: 4, semester: 7 },
];
